name: golden_matrix_example
description: Example usage of golden_matrix package.

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  golden_matrix:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
